#!/usr/bin/env python3
"""Build browser-ready graph payload for the live KG explorer."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "docs/knowledge-graph/artifact_registry.v0_1.json"
OUTPUT_PATH = REPO_ROOT / "docs/knowledge-graph/live/graph_data_autogenerated.json"


def propose_hsn(seed: str) -> tuple[int, int, int]:
    digest = hashlib.sha1(seed.encode("utf-8")).digest()
    return digest[0] % 12 + 1, digest[1] % 12 + 1, digest[2] % 12 + 1


def build_graph() -> dict:
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    artifacts = registry.get("artifacts", [])

    nodes = []
    links = []

    for artifact in artifacts:
        artifact_id = artifact["id"]
        h, s, n = propose_hsn(artifact_id)
        nodes.append(
            {
                "id": artifact_id,
                "name": artifact.get("title", artifact_id),
                "artifact_type": artifact.get("artifact_type", "unknown"),
                "status": artifact.get("status", "CANDIDATE"),
                "path": artifact.get("path", ""),
                "hsn": f"H{h:02d}-S{s:02d}-N{n:02d}",
                "x": h - 6.5,
                "y": s - 6.5,
                "z": n - 6.5,
            }
        )

        for relation in artifact.get("links", []):
            links.append(
                {
                    "source": artifact_id,
                    "target": relation.get("target_id"),
                    "relation": relation.get("relation", "relates_to"),
                }
            )

    return {
        "schema_version": registry.get("schema_version", "0.1"),
        "generated_from": str(REGISTRY_PATH.relative_to(REPO_ROOT)),
        "node_count": len(nodes),
        "edge_count": len(links),
        "nodes": nodes,
        "links": links,
    }


def main() -> None:
    graph = build_graph()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(graph, indent=2) + "\n", encoding="utf-8")
    print(f"nodes: {graph['node_count']}")
    print(f"edges: {graph['edge_count']}")
    print(f"written: {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
