#!/usr/bin/env python3
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "docs/knowledge-graph/artifact_registry.v0_1.json"
OUTPUT_PATH = REPO_ROOT / "docs/knowledge-graph/reverse_links_autogenerated.md"


def main() -> None:
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    artifacts = registry.get("artifacts", [])
    reverse_links = {artifact["id"]: [] for artifact in artifacts}

    for artifact in artifacts:
        for link in artifact.get("links", []):
            target_id = link["target_id"]
            if target_id in reverse_links and target_id != artifact["id"]:
                reverse_links[target_id].append(
                    {
                        "source_id": artifact["id"],
                        "source_title": artifact["title"],
                        "relation": link["relation"],
                    }
                )

    lines = [
        "# Reverse Links (Autogenerated)",
        "",
        "> **Status:** CANDIDATE  ",
        "> **Surface Type:** autogenerated reverse-link index  ",
        "> **Source:** `docs/knowledge-graph/artifact_registry.v0_1.json`",
        "",
        "## Reverse Link Table",
        "",
        "| Artifact ID | Title | Linked-to By |",
        "|---|---|---|",
    ]

    inbound_count = 0
    for artifact in artifacts:
        inbound = reverse_links[artifact["id"]]
        if inbound:
            inbound_count += 1
            linked_by = "<br>".join(
                f"`{entry['source_id']}` ({entry['relation']})"
                for entry in sorted(inbound, key=lambda item: item["source_id"])
            )
        else:
            linked_by = "—"
        lines.append(f"| `{artifact['id']}` | {artifact['title']} | {linked_by} |")

    completeness = (inbound_count / len(artifacts) * 100.0) if artifacts else 0.0
    lines.extend([
        "",
        "## Graph Completeness Score",
        "",
        f"{inbound_count} of {len(artifacts)} artifacts have at least one inbound link.",
        "",
        f"**Graph completeness score:** {completeness:.2f}%",
        "",
        "## Related Topics",
        "",
        "- [Knowledge Graph topic](../topics/knowledge-graph.md)",
        "- [Topics index](../topics/README.md)",
    ])

    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"reverse links written: {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    print(f"graph completeness score: {completeness:.2f}%")


if __name__ == "__main__":
    main()
