#!/usr/bin/env python3
"""Build static browser-search index from registered artifacts."""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "docs/knowledge-graph/artifact_registry.v0_1.json"
OUTPUT_PATH = REPO_ROOT / "docs/knowledge-graph/live/search_index_autogenerated.json"

MARKDOWN_CLEAN_RE = re.compile(r"[`*_>#\-\[\]\(\)]")
WHITESPACE_RE = re.compile(r"\s+")


def clean_text(raw: str) -> str:
    text = MARKDOWN_CLEAN_RE.sub(" ", raw)
    text = WHITESPACE_RE.sub(" ", text)
    return text.strip()


def read_excerpt(path: Path) -> str:
    if not path.exists() or path.is_dir():
        return ""
    text = path.read_text(encoding="utf-8", errors="ignore")
    cleaned = clean_text(text)
    return cleaned[:500]


def build_index() -> dict:
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    entries = []
    for artifact in registry.get("artifacts", []):
        rel_path = artifact.get("path", "")
        source = REPO_ROOT / rel_path if rel_path else REPO_ROOT
        entry = {
            "id": artifact.get("id", ""),
            "title": artifact.get("title", ""),
            "artifact_type": artifact.get("artifact_type", ""),
            "status": artifact.get("status", ""),
            "path": rel_path,
            "links": [f"{link.get('relation')}:{link.get('target_id')}" for link in artifact.get("links", [])],
            "excerpt": read_excerpt(source),
        }
        entries.append(entry)

    return {
        "generated_from": str(REGISTRY_PATH.relative_to(REPO_ROOT)),
        "entry_count": len(entries),
        "entries": entries,
    }


def main() -> None:
    payload = build_index()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"search entries: {payload['entry_count']}")
    print(f"written: {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
