#!/usr/bin/env python3
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "docs/knowledge-graph/artifact_registry.v0_1.json"
OUTPUT_PATH = REPO_ROOT / "docs/knowledge-graph/graph_index_autogenerated.json"


def main() -> None:
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    artifacts = registry.get("artifacts", [])

    nodes_by_id = {}
    for artifact in artifacts:
        nodes_by_id[artifact["id"]] = {
            "id": artifact["id"],
            "title": artifact["title"],
            "type": artifact["artifact_type"],
            "status": artifact["status"],
            "path": artifact["path"],
            "out_edges": [
                {
                    "relation": link["relation"],
                    "target_id": link["target_id"],
                }
                for link in artifact.get("links", [])
            ],
            "in_edges": [],
        }

    for node in nodes_by_id.values():
        for edge in node["out_edges"]:
            target = nodes_by_id.get(edge["target_id"])
            if target is None:
                continue
            target["in_edges"].append(
                {
                    "relation": edge["relation"],
                    "source_id": node["id"],
                }
            )

    nodes = list(nodes_by_id.values())
    total_nodes = len(nodes)
    total_edges = sum(len(node["out_edges"]) for node in nodes)
    density = total_edges / (total_nodes * (total_nodes - 1)) if total_nodes > 1 else 0.0
    largest_hub = max(nodes, key=lambda node: len(node["out_edges"]) + len(node["in_edges"]))

    graph = {
        "schema_version": registry.get("schema_version", "0.1"),
        "generated_from": str(REGISTRY_PATH.relative_to(REPO_ROOT)),
        "node_count": total_nodes,
        "edge_count": total_edges,
        "density_score": round(density, 6),
        "largest_hub": {
            "id": largest_hub["id"],
            "title": largest_hub["title"],
            "connections": len(largest_hub["out_edges"]) + len(largest_hub["in_edges"]),
        },
        "nodes": nodes,
    }

    OUTPUT_PATH.write_text(json.dumps(graph, indent=2) + "\n", encoding="utf-8")

    print(f"total nodes: {total_nodes}")
    print(f"total edges: {total_edges}")
    print(
        "largest hub: "
        f"{graph['largest_hub']['id']} ({graph['largest_hub']['title']}) - "
        f"{graph['largest_hub']['connections']} connections"
    )
    print(f"graph density score: {graph['density_score']:.6f}")


if __name__ == "__main__":
    main()
