#!/usr/bin/env python3
"""Build an autogenerated ingestion queue for unregistered markdown artifacts."""

from __future__ import annotations

import csv
import hashlib
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "docs/knowledge-graph/artifact_registry.v0_1.json"
OUTPUT_PATH = REPO_ROOT / "docs/intake/ip500_ingestion_queue_autogenerated.csv"
SCAN_DIRS = [
    "about",
    "docs",
    "projects",
    "archive",
    "health",
    "research",
    "aluminum-os",
    "bazinga",
    "manus-vault",
]
SKIP_PARTS = {".git", ".github", "node_modules", "target", "quarantine"}


def load_registry_paths() -> set[str]:
    payload = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    return {item.get("path", "") for item in payload.get("artifacts", []) if item.get("path")}


def classify_artifact(path: str) -> tuple[str, str]:
    lower = path.lower()
    if "schema" in lower or path.endswith(".schema.v0_1.json"):
        return "schema", "KG"
    if "workflow" in lower or "/workflows/" in lower:
        return "automation", "CI"
    if any(token in lower for token in ["charter", "doctrine", "policy"]):
        return "doctrine", "GOV"
    if any(token in lower for token in ["spec", "protocol", "contract"]):
        return "spec", "GP"
    if any(token in lower for token in ["report", "brief", "summary", "assessment"]):
        return "report", "RESEARCH"
    if any(token in lower for token in ["guide", "readme", "start_here", "glossary"]):
        return "guide", "ARCH"
    if "ledger" in lower or "evidence" in lower:
        return "evidence", "EVID"
    return "artifact", "ARCH"


def propose_id(path: str, prefix: str) -> str:
    digest = hashlib.sha1(path.encode("utf-8")).hexdigest()[:8].upper()
    return f"AL-{prefix}-{digest}"


def propose_hsn(path: str) -> str:
    digest = hashlib.sha1(path.encode("utf-8")).digest()
    h = digest[0] % 12 + 1
    s = digest[1] % 12 + 1
    n = digest[2] % 12 + 1
    return f"H{h:02d}-S{s:02d}-N{n:02d}"


def extract_title(content: str, fallback_name: str) -> str:
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip()
    return re.sub(r"[-_]+", " ", fallback_name).strip().title()


def should_skip(path: Path) -> bool:
    return any(part in SKIP_PARTS for part in path.parts)


def collect_unregistered_markdown(registered_paths: set[str]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    counter = 0
    for rel_dir in SCAN_DIRS:
        base = REPO_ROOT / rel_dir
        if not base.exists():
            continue
        for file_path in sorted(base.rglob("*.md")):
            if should_skip(file_path):
                continue
            rel_path = file_path.relative_to(REPO_ROOT).as_posix()
            if rel_path in registered_paths:
                continue

            text = file_path.read_text(encoding="utf-8", errors="ignore")
            title = extract_title(text, file_path.stem)
            artifact_type, prefix = classify_artifact(rel_path)
            counter += 1
            priority = 10 if rel_path.startswith("docs/") else 7
            rows.append(
                {
                    "queue_id": f"IQ-{counter:04d}",
                    "source_path": rel_path,
                    "title": title,
                    "domain": rel_path.split("/", 1)[0],
                    "artifact_type": artifact_type,
                    "proposed_id": propose_id(rel_path, prefix),
                    "proposed_hsn": propose_hsn(rel_path),
                    "status": "QUEUED",
                    "priority": str(priority),
                    "notes": "Autogenerated candidate for registry ingestion.",
                }
            )
    return rows


def main() -> None:
    registered_paths = load_registry_paths()
    rows = collect_unregistered_markdown(registered_paths)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "queue_id",
        "source_path",
        "title",
        "domain",
        "artifact_type",
        "proposed_id",
        "proposed_hsn",
        "status",
        "priority",
        "notes",
    ]

    with OUTPUT_PATH.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"queued artifacts: {len(rows)}")
    print(f"written: {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
