#!/usr/bin/env python3
"""Generate the weekly State of the Lattice report.

Reads the lattice global index and graph manifest to produce a markdown
summary of coverage, edge counts, new nodes, and open review items.
"""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path

INDEX_PATH = "archive/knowledge_graph/lattice_kg/v0_5/lattice_global_index.v0.1.json"
MANIFEST_PATH = "archive/knowledge_graph/lattice_kg/v0_5/lattice_graph_manifest.v1.0.json"
DEFS_PATH = "archive/knowledge_graph/lattice_kg/v0_5/HSN_AXIS_DEFINITIONS_v1.0.yaml"

HOUSE_LABELS = {
    "H01": "Matter", "H02": "Energy", "H03": "Acoustics", "H04": "Color",
    "H05": "Biology", "H06": "Mind", "H07": "Language", "H08": "Systems",
    "H09": "Knowledge", "H10": "Time", "H11": "Space", "H12": "Spirit",
}


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".", help="Repository root directory")
    parser.add_argument("--output", default="docs/STATE_OF_LATTICE_WEEKLY.md", help="Output file path")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    output_path = repo_root / args.output
    now_utc = datetime.now(UTC)
    report_date = now_utc.strftime("%Y-%m-%d")

    # Load index
    index_path = repo_root / INDEX_PATH
    index = load_json(index_path)
    artifacts = index.get("artifacts", [])
    hsn_coverage = index.get("hsn_coverage", {})
    link_health = index.get("link_health", {})

    # Load manifest (optional)
    manifest_path = repo_root / MANIFEST_PATH
    manifest: dict = {}
    if manifest_path.exists():
        manifest = load_json(manifest_path)

    total_nodes = manifest.get("stats", {}).get("total_nodes", len(artifacts))
    total_edges = manifest.get("stats", {}).get("total_edges", 0)
    distinct_hsn = manifest.get("stats", {}).get("distinct_hsn_coordinates", 0)
    hsn_pct = manifest.get("stats", {}).get("hsn_coverage_pct", 0.0)
    node_types = manifest.get("stats", {}).get("node_types", {})
    edge_types = manifest.get("stats", {}).get("edge_types", {})

    # House distribution
    house_counts: dict[str, int] = {}
    for art in artifacts:
        coord = art.get("hsn_coordinate", "")
        h = coord.split("-")[0] if coord else "unknown"
        house_counts[h] = house_counts.get(h, 0) + 1

    # Coverage stats
    total_artifacts = hsn_coverage.get("total_artifacts", len(artifacts))
    non_default = hsn_coverage.get("non_default_assignments", 0)
    default_coord = hsn_coverage.get("default_coordinate", "H09-S03-N05")
    coverage_pct = (non_default / total_artifacts * 100) if total_artifacts > 0 else 0.0

    # Markdown rows (cross-link health)
    md_total = link_health.get("markdown_artifacts_total", 0)
    md_underlinked = link_health.get("underlinked_markdown_artifacts", 0)
    md_isolated = link_health.get("isolated_markdown_artifacts", 0)
    md_root_reachable = link_health.get("root_reachable_markdown_artifacts", 0)
    unresolved_links = link_health.get("unresolved_repo_links", 0)

    # Build report
    lines: list[str] = [
        f"# State of the Lattice — Weekly Report",
        f"",
        f"> **Generated:** {report_date} (UTC)  ",
        f"> **Status:** CANDIDATE ONLY · NOT CANON  ",
        f"> **Authority:** This report is auto-generated by CI. No claim herein is canon until ratified.",
        f"",
        f"---",
        f"",
        f"## Graph Overview",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total nodes (manifest) | {total_nodes:,} |",
        f"| Total edges (manifest) | {total_edges:,} |",
        f"| Distinct H-S-N cells populated | {distinct_hsn} / 1,728 ({hsn_pct:.1f}%) |",
        f"| Artifact nodes | {node_types.get('artifact', len(artifacts)):,} |",
        f"| Element nodes (Periodic Table seed) | {node_types.get('element', 0):,} |",
        f"| Spectral band nodes (Rainbow seed) | {node_types.get('spectral_band', 0):,} |",
        f"| Chromatic note nodes | {node_types.get('chromatic_note', 0):,} |",
        f"",
        f"## Edge Breakdown",
        f"",
        f"| Edge Type | Count |",
        f"|-----------|-------|",
    ]
    for etype, cnt in sorted(edge_types.items(), key=lambda x: -x[1]):
        lines.append(f"| `{etype}` | {cnt} |")

    lines += [
        f"",
        f"## H-S-N Coverage",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total artifacts | {total_artifacts:,} |",
        f"| Non-default HSN assignments | {non_default:,} ({coverage_pct:.1f}%) |",
        f"| Default fallback coordinate | `{default_coord}` |",
        f"| Coverage target | ≥ 95% |",
        f"| Coverage status | {'✅ PASS' if coverage_pct >= 95.0 else '⚠️ BELOW TARGET'} |",
        f"",
        f"## House Distribution (artifacts)",
        f"",
        f"| House | Domain | Artifacts |",
        f"|-------|--------|-----------|",
    ]
    for h in [f"H{str(i).zfill(2)}" for i in range(1, 13)]:
        count = house_counts.get(h, 0)
        bar = "█" * min(count // 10, 30)
        lines.append(f"| `{h}` | {HOUSE_LABELS.get(h, '')} | {count} {bar} |")

    lines += [
        f"",
        f"## Link Health (Markdown artifacts)",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total markdown artifacts | {md_total:,} |",
        f"| Root-reachable from README | {md_root_reachable:,} |",
        f"| Underlinked (zero outbound) | {md_underlinked:,} |",
        f"| Isolated (zero in+out) | {md_isolated:,} |",
        f"| Unresolved repo links | {unresolved_links:,} |",
        f"",
        f"## Open Review Items",
        f"",
        f"All artifacts are at `trust_state: candidate_unverified` pending Pantheon Council ratification",
        f"and adjudication by @atlaslattice. The following gates must pass before any artifact advances:",
        f"",
        f"- [ ] 100% HSN coordinate assignment (current: {coverage_pct:.1f}%)",
        f"- [ ] Zero unresolved repo links (current: {unresolved_links})",
        f"- [ ] Graph manifest validated and schema-compliant",
        f"- [ ] Full council ratification event recorded",
        f"- [ ] Human adjudication by @atlaslattice",
        f"",
        f"## Query the Lattice",
        f"",
        f"```bash",
        f"# Get stats",
        f"python scripts/query_lattice.py --stats",
        f"",
        f"# Query a specific coordinate",
        f"python scripts/query_lattice.py H01-S06-N01",
        f"",
        f"# List all populated cells",
        f"python scripts/query_lattice.py --list-all-coords",
        f"",
        f"# Filter by house",
        f"python scripts/query_lattice.py --house H04",
        f"```",
        f"",
        f"## Interactive Graph",
        f"",
        f"The 3D graph viewer is available at [docs/graph/index.html](docs/graph/index.html).",
        f"When deployed via GitHub Pages, visit `https://atlaslattice.github.io/manus-artifacts/graph/`.",
        f"",
        f"---",
        f"",
        f"*Auto-generated by `.github/workflows/state-of-lattice-weekly.yml` — CANDIDATE NOT CANON*",
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Report written to {output_path.relative_to(repo_root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
