name: Markdown Lint

on:
  push:
    paths:
      - "**/*.md"
      - ".github/workflows/markdown-lint.yml"
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/markdown-lint.yml"

permissions:
  contents: read

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            README.md
            docs/*.md
            .github/*.md
